[package]
name = "rustful"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
axum = "0.5.4"
futures = "0.3.19"
num_cpus = "1.13.1"
async-trait = "0.1.52"
serde_json = "1.0.79"
#matchit = "0.5.0"
bytes = { version = "1", features = ["serde"] }
